name: nebulant

services:
  bridge:
    container_name: nebulant_bridge
    build:
      context: .
      dockerfile: Dockerfile
    image: develatio/nebulant_bridge
    command: "/app/dist/nebulant-bridge -x -b 0.0.0.0:16789 -bs ultrasecret"
    networks:
      - nebulant-private
      - nebulant-lan
  # cli:
  #   container_name: develatio/nebulant_cli
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   image: develatio/nebulant_cli
  #   command: "/app/dist/nebulant -x serve"
  #   ports:
  #     - 15678:15678
  #   networks:
  #     - nebulant
  #     - nebulant-external
  buildenv:
    container_name: nebulant_cli_build_environment
    build:
      context: .
      dockerfile: Dockerfile
    image: develatio/nebulant_cli
    volumes:
      - ./:/app

networks:
  nebulant-private:
    name: nebulant-private
  nebulant-lan:
    name: nebulant-lan
    external: true
