package term

var EmojiSet map[string]string = map[string]string{
	"FaceScreamingInFear":          "😱",
	"PoliceCarLight":               "🚨",
	"Construction":                 "🚧",
	"Wrench":                       "🔧",
	"BackhandIndexPointingRight":   "👉",
	"ConstructionWorker":           "👷",
	"HighVoltage":                  "⚡",
	"CardIndexDividers":            "🗂️",
	"Elevator":                     "🛗",
	"Rocket":                       "🚀",
	"ThumbsUpSign":                 "👍",
	"Television":                   "📺",
	"Squid":                        "🦑",
	"TridentEmblem":                "🔱",
	"RunningShoe":                  "👟",
	"Key":                          "🔑",
	"FaceWithMonocle":              "🧐",
	"Ambulance":                    "🚑",
	"Dizzy":                        "💫",
	"CounterclockwiseArrowsButton": "🔄",
	"WhiteQuestionMark":            "❔",
	"Sparkles":                     "✨",
	"CheckMarkButton":              "✅",
	"CrossMarkButton":              "❎",
	"CrossMark":                    "❌",
}

var noEmojiSupportSet map[string]string = map[string]string{
	"FaceScreamingInFear":          "!!",
	"PoliceCarLight":               "E ",
	"Construction":                 "W ",
	"Wrench":                       "* ",
	"BackhandIndexPointingRight":   "->",
	"ConstructionWorker":           "  ",
	"HighVoltage":                  "  ",
	"CardIndexDividers":            "  ",
	"Elevator":                     "  ",
	"Rocket":                       "  ",
	"ThumbsUpSign":                 "  ",
	"Television":                   "  ",
	"Squid":                        "  ",
	"TridentEmblem":                "  ",
	"RunningShoe":                  "  ",
	"Key":                          "  ",
	"FaceWithMonocle":              "  ",
	"Ambulance":                    "  ",
	"Dizzy":                        "･ﾟ✧",
	"CounterclockwiseArrowsButton": "  ",
	"WhiteQuestionMark":            "? ",
	"Sparkles":                     "*:",
	"CheckMarkButton":              "VV",
	"CrossMarkButton":              "--",
	"CrossMark":                    "XX",
}
